name: bugcash_web_demo
description: BugCash Web Demo - Bug testing platform
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # Core
  equatable: ^2.0.5
  dartz: ^0.10.1
  
  # UI
  flutter_screenutil: ^5.9.0
  google_fonts: ^6.1.0
  
  # Utils
  intl: ^0.19.0
  url_launcher: ^6.2.1
  
  # Firebase
  firebase_core: ^3.8.0
  cloud_firestore: ^5.5.0
  firebase_auth: ^5.3.3
  firebase_storage: ^12.3.6
  firebase_messaging: ^15.1.5
  
  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  flutter_bloc: ^8.1.3
  
  # Dependency Injection  
  get_it: ^7.6.4
  injectable: ^2.3.2
  
  # Authentication
  google_sign_in: ^6.1.6
  
  # Image Picking
  image_picker: ^1.0.7
  
  
  # Additional Utils
  uuid: ^4.2.1
  shared_preferences: ^2.2.2
  
  # Notifications
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.4
  
  # Connectivity
  connectivity_plus: ^6.1.0

  # AI
  google_generative_ai: ^0.4.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  injectable_generator: ^2.4.1
  build_runner: ^2.4.7
  riverpod_generator: ^2.3.9
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icons/app_icon.png"
    background_color: "#000000"
    theme_color: "#FFD700"
  windows:
    generate: true
    image_path: "assets/icons/app_icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icons/app_icon.png"