name: bugcash_web_demo
description: BugCash Web Demo - Bug testing platform
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  
  # UI
  flutter_screenutil: ^5.9.0
  google_fonts: ^6.1.0
  
  # Utils
  intl: ^0.19.0
  url_launcher: ^6.2.1
  flutter_dotenv: ^5.1.0
  
  # Firebase
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.1
  firebase_storage: ^12.3.2
  firebase_messaging: ^15.1.3
  
  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  
  # Dependency Injection  
  get_it: ^7.6.4
  injectable: ^2.3.2
  
  # Authentication
  google_sign_in: ^6.1.6
  
  # Image Picking
  image_picker: ^1.0.7
  
  
  # Additional Utils
  uuid: ^4.2.1
  shared_preferences: ^2.2.2
  
  # Notifications
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.4
  
  # Connectivity
  connectivity_plus: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  injectable_generator: ^2.4.1
  build_runner: ^2.4.7
  riverpod_generator: ^2.3.9

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/
    - .env