name: bugcash_web_demo
description: BugCash Web Demo - Bug testing platform
publish_to: 'none'
version: 2.186.16+206

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # Core
  equatable: ^2.0.5
  dartz: ^0.10.1
  
  # UI
  flutter_screenutil: ^5.9.0
  google_fonts: ^6.1.0
  flutter_markdown: ^0.7.4+1
  
  # Utils
  intl: ^0.19.0
  url_launcher: ^6.2.1
  csv: ^6.0.0  # v2.184.0: CSV 파일 생성 및 다운로드
  universal_html: ^2.2.4  # v2.185.4: 크로스 플랫폼 HTML 지원
  
  # Firebase
  firebase_core: ^3.8.0
  cloud_firestore: ^5.5.0
  firebase_auth: ^5.3.3
  firebase_storage: ^12.4.10
  firebase_messaging: ^15.1.5
  cloud_functions: ^5.1.3

  # v2.115.0: Google Cloud Storage API 직접 호출 (Firebase Storage SDK 우회)
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  
  # State Management
  flutter_riverpod: ^2.4.9
  freezed_annotation: ^2.4.1
  
  # Authentication
  google_sign_in: ^6.1.6
  
  # Additional Utils
  uuid: ^4.2.1
  shared_preferences: ^2.2.2
  flutter_dotenv: ^5.1.0
  image_picker: ^1.0.7
  dio: ^5.4.0
  path_provider: ^2.1.1

  # Payment
  tosspayments_widget_sdk_flutter: ^2.1.2
  webview_flutter: ^4.4.2
  http: ^1.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  riverpod_generator: ^2.3.9
  flutter_launcher_icons: ^0.13.1
  freezed: ^2.4.5
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/
    - .env

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icons/app_icon.png"
    background_color: "#000000"
    theme_color: "#FFD700"
  windows:
    generate: true
    image_path: "assets/icons/app_icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icons/app_icon.png"