// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeMQcgKwJR5smPY6t6tnDtNdqaPoCamk0',
    appId: '1:335851774651:web:f7efbf71fdfd36690abf9e',
    messagingSenderId: '335851774651',
    projectId: 'bugcash',
    authDomain: 'bugcash.firebaseapp.com',
    storageBucket: 'bugcash.firebasestorage.app',
    measurementId: 'G-M1DT15JR9G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0hLevMSRKZpoMaF4Sb_YgvR7ED1VR6Xo',
    appId: '1:335851774651:android:9c485dd2a5f436ef0abf9e',
    messagingSenderId: '335851774651',
    projectId: 'bugcash',
    storageBucket: 'bugcash.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3EY_your_ios_api_key_here',
    appId: '1:335851774651:ios:abcdef123456789',
    messagingSenderId: '335851774651',
    projectId: 'bugcash',
    storageBucket: 'bugcash.appspot.com',
    iosClientId: 'YOUR_IOS_CLIENT_ID.apps.googleusercontent.com',
    iosBundleId: 'com.bugcash.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4EY_your_macos_api_key_here',
    appId: '1:335851774651:macos:abcdef123456789',
    messagingSenderId: '335851774651',
    projectId: 'bugcash',
    storageBucket: 'bugcash.appspot.com',
    iosClientId: 'YOUR_MACOS_CLIENT_ID.apps.googleusercontent.com',
    iosBundleId: 'com.bugcash.app',
  );
}